import { isIP } from "node:net";
import { isBlockedIp } from "./security";

export type RdapStatus = "success" | "no_data" | "timeout" | "http_error" | "malformed";
export type RdapResult = { status: RdapStatus; ip: string; source: "rdap"; network?: { cidr?: string; startAddress?: string; endAddress?: string; handle?: string; name?: string; country?: string; registry?: string }; asns: string[]; organization?: string; raw?: unknown; error?: string; duration_ms: number };
const MAX_RESPONSE = 2_000_000;
const bootstrapUrl = (ip: string) => isIP(ip) === 6 ? "https://data.iana.org/rdap/ipv6.json" : "https://data.iana.org/rdap/ipv4.json";
const ipv4Number = (ip: string) => ip.split(".").reduce((n, part) => n * 256 + Number(part), 0);
function prefixMatches(ip: string, prefix: string) { if (isIP(ip) !== isIP(prefix.split("/")[0])) return false; const [base, bitsText] = prefix.split("/"); const bits = Number(bitsText); if (isIP(ip) === 4) { const mask = bits === 0 ? 0 : (0xffffffff << (32 - bits)) >>> 0; return (ipv4Number(ip) & mask) === (ipv4Number(base) & mask); } const parse6 = (value: string) => { const [left, right = ""] = value.split("::"); const l = left ? left.split(":") : []; const r = right ? right.split(":") : []; const groups = [...l, ...Array(8 - l.length - r.length).fill("0"), ...r]; return groups.reduce((n, group) => (n << 16n) + BigInt(parseInt(group || "0", 16)), 0n); }; const mask = bits === 0 ? 0n : ((1n << 128n) - 1n) ^ ((1n << BigInt(128 - bits)) - 1n); return (parse6(ip) & mask) === (parse6(base) & mask); }
export function selectRdapEndpoint(ip: string, bootstrap: any) { const services = Array.isArray(bootstrap?.services) ? bootstrap.services : []; const matches = services.flatMap((entry: any[]) => { const prefixes = Array.isArray(entry?.[0]) ? entry[0] : []; const urls = Array.isArray(entry?.[1]) ? entry[1] : []; return prefixes.filter((prefix: string) => prefixMatches(ip, prefix)).flatMap(() => urls); }); return matches[0]?.replace(/\/$/, ""); }
export function normalizeRdapIp(ip: string) { if (!isIP(ip) || isBlockedIp(ip)) throw new Error("RDAP requires a public IP"); return ip.toLowerCase(); }
export function parseRdap(ip: string, body: any): Omit<RdapResult, "duration_ms" | "ip"> { const cidrEntry = body?.cidr0_cidrs?.[0]; const cidr = cidrEntry ? `${cidrEntry.v4prefix ?? cidrEntry.v6prefix}/${cidrEntry.length}` : undefined; const network = body?.startAddress || body?.endAddress || body?.handle || body?.name ? { cidr, startAddress: body.startAddress, endAddress: body.endAddress, handle: body.handle, name: body.name, country: body.country, registry: body.port43 } : undefined; const entities = Array.isArray(body?.entities) ? body.entities : []; const organization = entities.flatMap((entity: any) => entity.vcardArray?.[1] ?? []).find((item: any) => item?.[0] === "fn")?.[3] ?? body?.name; const asns = [...new Set([...(body?.asn ? [String(body.asn)] : []), ...(body?.remarks ?? []).flatMap((r: any) => String(r?.description ?? "").match(/AS\d+/gi) ?? [])])]; if (!network && !organization && !asns.length) return { status: "no_data", source: "rdap", asns: [] }; return { status: "success", source: "rdap", network, organization, asns, raw: body }; }
async function requestJson(url: string, controller: AbortController) { const response = await fetch(url, { signal: controller.signal, redirect: "follow", headers: { accept: "application/rdap+json, application/json", "user-agent": "Infrastructure-Intelligence/0.1" } }); if (!response.ok) throw Object.assign(new Error(`HTTP ${response.status}`), { status: response.status }); const text = await response.text(); if (text.length > MAX_RESPONSE) throw new Error("Response exceeds limit"); try { return JSON.parse(text); } catch { throw new Error("Malformed JSON"); } }
export async function lookupRdap(ipValue: string, timeoutMs = 8_000): Promise<RdapResult> { const ip = normalizeRdapIp(ipValue); const started = Date.now(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const bootstrap = await requestJson(bootstrapUrl(ip), controller); const endpoint = selectRdapEndpoint(ip, bootstrap); if (!endpoint) return { status: "no_data", ip, source: "rdap", asns: [], error: "No RDAP service for IP", duration_ms: Date.now() - started }; const body = await requestJson(`${endpoint}/ip/${encodeURIComponent(ip)}`, controller); return { ip, duration_ms: Date.now() - started, ...parseRdap(ip, body) }; } catch (error: any) { const status: RdapStatus = error?.name === "AbortError" ? "timeout" : error?.message === "Malformed JSON" ? "malformed" : "http_error"; return { status, ip, source: "rdap", asns: [], error: error instanceof Error ? error.message : "RDAP request failed", duration_ms: Date.now() - started }; } finally { clearTimeout(timer); } }
