import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import { request as httpRequest } from "node:http";
import { request as httpsRequest } from "node:https";

const blockedNames = new Set(["localhost", "metadata.google.internal", "metadata.azure.com", "instance-data.ec2.internal"]);
const privateV4 = (a: number, b: number, c: number) => a === 0 || a === 10 || a === 127 || a >= 224 || (a === 100 && b >= 64 && b <= 127) || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && (b === 0 || b === 168)) || (a === 198 && ((b >= 18 && b <= 19) || (b === 51 && c === 100))) || (a === 203 && b === 0 && c === 113);
export type SafeHttpResponse = { status: number; headers: Headers; text: () => Promise<string> };
export function normalizeDomain(input: string): string { const value = input.trim().toLowerCase().replace(/\.$/, ""); if (!/^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(value)) throw new Error("Invalid domain"); return value; }
export function isInScope(host: string, scope: string) { return host === scope || host.endsWith(`.${scope}`); }
export function isBlockedIp(value: string): boolean { if (isIP(value) === 4) { const [a,b,c] = value.split(".").map(Number); return privateV4(a,b,c); } const ip = value.toLowerCase(); if (ip.startsWith("::ffff:")) return isBlockedIp(ip.slice(7)); return ip === "::" || ip === "::1" || ip.startsWith("fc") || ip.startsWith("fd") || ip.startsWith("fe80:") || ip.startsWith("ff") || ip.startsWith("2001:db8:"); }
export async function assertSafeHost(host: string): Promise<string[]> { const normalized = normalizeDomain(host); if (blockedNames.has(normalized)) throw new Error("Blocked destination"); const answers = await lookup(normalized, { all: true, verbatim: true }); if (!answers.length || answers.some(answer => isBlockedIp(answer.address))) throw new Error("Destination resolves to a blocked address"); return answers.map(answer => answer.address); }
function requestPinned(url: URL, host: string, ip: string, init: RequestInit): Promise<SafeHttpResponse> {
  const headers: Record<string, string> = { host, "user-agent": "Infrastructure-Intelligence/0.1 (authorized discovery)", range: "bytes=0-65536" };
  new Headers(init.headers).forEach((value, key) => { headers[key] = value; });
  const options = { protocol: url.protocol, hostname: ip, port: url.port || undefined, path: `${url.pathname}${url.search}`, method: init.method ?? "GET", servername: host, rejectUnauthorized: true, headers, timeout: 8_000 } as never;
  const transport = url.protocol === "https:" ? httpsRequest : httpRequest;
  return new Promise((resolve, reject) => { const request = transport(options, response => { const chunks: Buffer[] = []; let size = 0; response.on("data", (chunk: Buffer) => { size += chunk.length; if (size <= 65_536) chunks.push(chunk); else request.destroy(new Error("Response exceeds inspection limit")); }); response.on("end", () => { const responseHeaders: [string, string][] = Object.entries(response.headers).flatMap(([key,value]) => value === undefined ? [] : [[key, Array.isArray(value) ? value.join(", ") : String(value)]]); resolve({ status: response.statusCode ?? 0, headers: new Headers(responseHeaders), text: async () => Buffer.concat(chunks).toString("utf8") }); }); }); request.on("timeout", () => request.destroy(new Error("Request timed out"))); request.on("error", reject); request.end(); });
}
/** Resolve once, validate every result, and dial the exact validated IP. */
export async function safeFetch(urlValue: string, scope: string, init: RequestInit = {}): Promise<SafeHttpResponse> { const url = new URL(urlValue); if (url.protocol !== "https:" && url.protocol !== "http:") throw new Error("Unsupported protocol"); const host = normalizeDomain(url.hostname); if (!isInScope(host, scope)) throw new Error("Destination outside verified scope"); const addresses = await assertSafeHost(host); let error: unknown; for (const address of addresses) { try { const response = await requestPinned(url, host, address, init); const location = response.headers.get("location"); if (location && response.status >= 300 && response.status < 400) { const redirect = new URL(location, url); const redirectHost = normalizeDomain(redirect.hostname); if (!isInScope(redirectHost, scope)) throw new Error("Redirect outside verified scope"); await assertSafeHost(redirectHost); } return response; } catch (caught) { error = caught; } } throw error instanceof Error ? error : new Error("No safe destination available"); }
