"use client";

import { useMemo, useState } from "react";
import { formatUtcDate } from "./DeterministicDate";

type Scope = { id: string; domain: string; status: string; verificationMethod: string | null; verifiedAt: string | Date | null };
type Asset = { id: string; type: string; displayName: string; ownership?: string; lastSeenAt: string | Date; status: string };
type Run = { id: string; scopeId: string; status: string; summary: Record<string, any>; createdAt: string | Date };
type Verification = { record?: string; path?: string; value: string };
const labels: Record<string, string> = { domain: "Domains", subdomain: "Subdomains", ip_address: "IP addresses", tls_certificate: "Certificates", web_service: "Services", infrastructure_provider: "Providers" };

export default function DashboardClient({ initialScopes, initialAssets, initialRuns }: { initialScopes: Scope[]; initialAssets: Asset[]; initialRuns: Run[] }) {
  const [scopes, setScopes] = useState(initialScopes); const [assets, setAssets] = useState(initialAssets); const [runs, setRuns] = useState(initialRuns); const [domain, setDomain] = useState(""); const [method, setMethod] = useState<"dns_txt" | "http">("dns_txt"); const [verification, setVerification] = useState<Verification>(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const latestRun = runs[0];
  const counts = useMemo(() => Object.fromEntries(Object.keys(labels).map(type => [type, assets.filter(asset => asset.type === type).length])), [assets]);
  async function addScope(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch("/api/scopes", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ domain, method }) }); const result = await response.json(); if (!response.ok) setMessage(result.error ?? "Could not add domain"); else { setScopes(current => [result.scope, ...current]); setVerification(result.verification); setDomain(""); } setBusy(false); }
  async function verify(scope: Scope) { setBusy(true); setMessage(""); try { const response = await fetch(`/api/scopes/${scope.id}/verify`, { method: "POST" }); const result = await response.json().catch(() => ({})); if (result.verified) setScopes(current => current.map(item => item.id === scope.id ? { ...item, status: "verified", verifiedAt: new Date() } : item)); else setMessage(result.detail ?? result.error ?? "We could not find the verification record yet. DNS changes can take a few minutes."); } catch { setMessage("Verification request failed. Check that the application is running and try again."); } finally { setBusy(false); } }
  async function discover(scope: Scope) { setBusy(true); setMessage(""); const response = await fetch("/api/discovery", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ scopeId: scope.id }) }); const result = await response.json(); if (!response.ok) setMessage(result.error ?? "Could not start discovery"); else { setRuns(current => [{ ...result, summary: {} }, ...current]); poll(result.id); } setBusy(false); }
  async function poll(runId: string) { for (let attempt = 0; attempt < 120; attempt++) { await new Promise(resolve => setTimeout(resolve, 2500)); const response = await fetch(`/api/discovery/status?runId=${encodeURIComponent(runId)}`, { cache: "no-store" }); if (!response.ok) return; const result = await response.json(); setRuns(current => current.map(run => run.id === runId ? result.run : run)); if (result.run.status === "completed" || result.run.status === "failed") { setAssets(result.assets); return; } } }
  return <div className="dashboard-grid"><section className="main-column"><div className="page-heading"><div><span className="eyebrow">Workspace overview</span><h1>Infrastructure at a glance</h1><p className="muted">Start with a verified domain. We only inspect assets you authorize.</p></div><a className="secondary button-link" href="/graph">Open graph ↗</a></div>
    <div className="metric-grid">{Object.entries(labels).map(([type, label]) => <div className="metric-card" key={type}><span className="metric-icon">{type === "ip_address" ? "⌁" : type === "web_service" ? "◉" : "◇"}</span><strong>{counts[type]}</strong><span>{label}</span></div>)}</div>
    <section className="panel"><div className="panel-heading"><div><h2>Authorized domains</h2><p className="muted">Verify ownership before discovery can begin.</p></div></div>{scopes.length === 0 ? <div className="empty-state"><div className="empty-icon">◎</div><h3>Add your first domain</h3><p>We will map its public DNS, TLS and web services without intrusive scanning.</p></div> : <div className="scope-list">{scopes.map(scope => <div className="scope-row" key={scope.id}><div className="scope-name"><span className={`status-dot ${scope.status}`} /> <strong>{scope.domain}</strong><span className={`status-pill ${scope.status}`}>{scope.status === "verified" ? "Verified" : "Needs verification"}</span></div><div>{scope.status === "verified" ? <button className="primary small" disabled={busy} onClick={() => discover(scope)}>Discover infrastructure</button> : <button className="secondary small" disabled={busy} onClick={() => verify(scope)}>Check verification</button>}</div></div>)}</div>}</section>
    {verification && <section className="panel verification-panel"><div className="panel-heading"><div><h2>Verify {verification.record?.replace("_infrastructure-intelligence.", "") ?? "your domain"}</h2><p className="muted">Add this value, then return here and check verification.</p></div><button className="icon-button" onClick={() => setVerification(undefined)}>×</button></div><div className="verification-box"><span className="eyebrow">{verification.record ? "DNS TXT" : "HTTP file"}</span><code>{verification.record ?? verification.path}</code><div className="copy-row"><code>{verification.value}</code><button className="secondary small" onClick={() => navigator.clipboard?.writeText(verification.value)}>Copy</button></div></div></section>}
    {message && <div className="form-error" role="alert">{message}</div>}
    <section className="panel add-domain"><div className="panel-heading"><div><h2>Add a domain</h2><p className="muted">Only domains you control and authorize.</p></div></div><form onSubmit={addScope} className="domain-form"><input value={domain} onChange={event => setDomain(event.target.value)} required placeholder="example.com" /><select value={method} onChange={event => setMethod(event.target.value as "dns_txt" | "http")}><option value="dns_txt">DNS TXT verification</option><option value="http">HTTP /.well-known/ verification</option></select><button className="primary" disabled={busy}>{busy ? "Adding…" : "Add domain"}</button></form></section>
    <section className="panel"><div className="panel-heading"><div><h2>Recent discovery</h2><p className="muted">Results update automatically while a run is active.</p></div></div>{latestRun ? <div className="run-card"><span className={`status-pill ${latestRun.status}`}>{latestRun.status === "running" || latestRun.status === "queued" ? "Discovery running" : `Discovery ${latestRun.status}`}</span><strong>{latestRun.summary?.scopes_analyzed ? `${latestRun.summary.scopes_analyzed} scope analyzed` : "Collecting public infrastructure…"}</strong><span className="muted">{formatUtcDate(latestRun.createdAt)}</span></div> : <div className="empty-state compact"><p>No discovery runs yet.</p></div>}</section>
  </section><aside className="side-column"><section className="panel quick-panel"><span className="eyebrow">Quick start</span><h2>Map your exposure in three steps</h2><ol><li className={scopes.length ? "done" : ""}>Add a domain you control</li><li className={scopes.some(scope => scope.status === "verified") ? "done" : ""}>Verify ownership</li><li className={latestRun ? "done" : ""}>Discover infrastructure</li></ol><p className="muted">Discovery is passive-first, rate-limited and never attempts exploitation.</p></section><section className="panel"><h2>Assets</h2>{assets.length ? <div className="asset-preview">{assets.slice(0, 8).map(asset => <a href={`/assets/${asset.id}`} key={asset.id}><span>{asset.type.replaceAll("_", " ")}</span><strong>{asset.displayName}</strong></a>)}</div> : <div className="empty-state compact"><p>Assets will appear here after discovery.</p></div>}<a className="text-link" href="/assets">View all assets →</a></section></aside></div>;
}
