import { pgTable, uuid, text, timestamp, jsonb, integer, boolean, uniqueIndex, index } from "drizzle-orm/pg-core";

const id = () => uuid("id").defaultRandom().primaryKey();
const dates = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const tenants = pgTable("tenants", { id: id(), name: text("name").notNull(), slug: text("slug").notNull().unique(), ...dates });
export const users = pgTable("users", { id: id(), email: text("email").notNull().unique(), passwordHash: text("password_hash").notNull(), name: text("name").notNull(), ...dates });
export const memberships = pgTable("memberships", { id: id(), tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), role: text("role").notNull().default("member"), ...dates }, t => [uniqueIndex("membership_tenant_user").on(t.tenantId, t.userId)]);
export const scopes = pgTable("scopes", { id: id(), tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), domain: text("domain").notNull(), status: text("status").notNull().default("pending"), verificationMethod: text("verification_method"), verifiedAt: timestamp("verified_at", { withTimezone: true }), ...dates }, t => [uniqueIndex("scope_tenant_domain").on(t.tenantId, t.domain)]);
export const verificationChallenges = pgTable("verification_challenges", { id: id(), scopeId: uuid("scope_id").notNull().references(() => scopes.id, { onDelete: "cascade" }), method: text("method").notNull(), tokenHash: text("token_hash").notNull(), tokenPreview: text("token_preview").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), ...dates });
export const jobs = pgTable("jobs", { id: id(), tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), type: text("type").notNull(), payload: jsonb("payload").notNull(), status: text("status").notNull().default("queued"), attempts: integer("attempts").notNull().default(0), runAt: timestamp("run_at", { withTimezone: true }).defaultNow().notNull(), lockedAt: timestamp("locked_at", { withTimezone: true }), lastError: text("last_error"), ...dates }, t => [index("jobs_status_run_at").on(t.status, t.runAt)]);
export const discoveryRuns = pgTable("discovery_runs", { id: id(), tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), scopeId: uuid("scope_id").notNull().references(() => scopes.id, { onDelete: "cascade" }), status: text("status").notNull().default("queued"), pipelineVersion: text("pipeline_version").notNull().default("0.1"), startedAt: timestamp("started_at", { withTimezone: true }), finishedAt: timestamp("finished_at", { withTimezone: true }), summary: jsonb("summary").notNull().default({}), ...dates });
export const assets = pgTable("assets", { id: id(), tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), scopeId: uuid("scope_id").notNull().references(() => scopes.id, { onDelete: "cascade" }), type: text("type").notNull(), ownership: text("ownership").notNull().default("unknown"), canonicalKey: text("canonical_key").notNull(), displayName: text("display_name").notNull(), metadata: jsonb("metadata").notNull().default({}), status: text("status").notNull().default("active"), firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).defaultNow().notNull(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(), ...dates }, t => [uniqueIndex("asset_identity").on(t.tenantId, t.scopeId, t.type, t.canonicalKey), index("assets_scope_type").on(t.scopeId, t.type), index("assets_scope_ownership").on(t.scopeId, t.ownership)]);
export const assetObservations = pgTable("asset_observations", { id: id(), assetId: uuid("asset_id").notNull().references(() => assets.id, { onDelete: "cascade" }), runId: uuid("run_id").references(() => discoveryRuns.id, { onDelete: "set null" }), source: text("source").notNull(), observedAt: timestamp("observed_at", { withTimezone: true }).defaultNow().notNull(), rawValue: text("raw_value").notNull(), normalizedValue: text("normalized_value").notNull(), evidence: jsonb("evidence").notNull().default({}), confidence: integer("confidence").notNull() });
export const relationships = pgTable("relationships", { id: id(), tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), scopeId: uuid("scope_id").notNull().references(() => scopes.id, { onDelete: "cascade" }), sourceAssetId: uuid("source_asset_id").notNull().references(() => assets.id, { onDelete: "cascade" }), targetAssetId: uuid("target_asset_id").notNull().references(() => assets.id, { onDelete: "cascade" }), type: text("type").notNull(), qualifiers: jsonb("qualifiers").notNull().default({}), state: text("state").notNull().default("active"), confidence: integer("confidence").notNull(), firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).defaultNow().notNull(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(), ...dates }, t => [uniqueIndex("relationship_identity").on(t.sourceAssetId, t.targetAssetId, t.type), index("relationships_scope").on(t.scopeId)]);
export const relationshipObservations = pgTable("relationship_observations", { id: id(), relationshipId: uuid("relationship_id").notNull().references(() => relationships.id, { onDelete: "cascade" }), runId: uuid("run_id").references(() => discoveryRuns.id, { onDelete: "set null" }), source: text("source").notNull(), observedAt: timestamp("observed_at", { withTimezone: true }).defaultNow().notNull(), rawValue: text("raw_value").notNull(), normalizedValue: text("normalized_value").notNull(), evidence: jsonb("evidence").notNull().default({}), confidence: integer("confidence").notNull() });
export const changes = pgTable("changes", { id: id(), tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), scopeId: uuid("scope_id").notNull().references(() => scopes.id, { onDelete: "cascade" }), runId: uuid("run_id").references(() => discoveryRuns.id, { onDelete: "set null" }), entityType: text("entity_type").notNull(), entityId: uuid("entity_id").notNull(), changeType: text("change_type").notNull(), before: jsonb("before"), after: jsonb("after"), detectedAt: timestamp("detected_at", { withTimezone: true }).defaultNow().notNull() });
export const auditEvents = pgTable("audit_events", { id: id(), tenantId: uuid("tenant_id").references(() => tenants.id, { onDelete: "cascade" }), userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }), action: text("action").notNull(), targetType: text("target_type").notNull(), targetId: text("target_id"), metadata: jsonb("metadata").notNull().default({}), ipHash: text("ip_hash"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const rateLimits = pgTable("rate_limits", { id: id(), key: text("key").notNull(), windowStart: timestamp("window_start", { withTimezone: true }).notNull(), count: integer("count").notNull().default(0), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, t => [uniqueIndex("rate_limit_key_window").on(t.key, t.windowStart)]);
