// @ts-nocheck
"use client";
import { useEffect,useRef,useState } from "react";
import cytoscape,{type ElementDefinition} from "cytoscape";
type Data={id:string;label?:string;displayName?:string;source?:string;target?:string;ownership?:string;type?:string;confidence?:number;evidence?:unknown;firstSeenAt?:string;lastSeenAt?:string;[key:string]:unknown}; type Item={data:Data};
const labels:Record<string,string>={HAS_MX:"MX",HAS_NAMESERVER:"NS",HAS_TXT:"DNS",HAS_SOA:"DNS",RESOLVES_TO:"DNS",PRESENTS_CERTIFICATE:"TLS",USES_PROVIDER:"USES",HOSTS_SERVICE:"HOSTS",CNAME_TO:"DNS",SUBDOMAIN_OF:"DNS"};
export default function GraphPage(){const ref=useRef<HTMLDivElement>(null);const cy=useRef<cytoscape.Core|null>(null);const[mode,setMode]=useState<"overview"|"detailed">("overview");const[msg,setMsg]=useState("Loading infrastructure…");const[selected,setSelected]=useState<Data>();const[relation,setRelation]=useState<Data>();
// @ts-ignore Cytoscape style definitions are runtime-validated by the library.
useEffect(()=>{let dead=false;fetch("/api/graph",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<Item[]>}).then(all=>{if(dead||!ref.current)return;const nodes=all.filter(x=>!x.data.source),ids=new Set(nodes.map(x=>x.data.id));let items=all.filter(x=>!x.data.source||(typeof x.data.source==="string"&&typeof x.data.target==="string"&&ids.has(x.data.source)&&ids.has(x.data.target)));if(mode==="overview"){const keep=new Set(nodes.filter(x=>["domain","subdomain","ip_address","web_service","tls_certificate","infrastructure_provider"].includes(String(x.data.type))||x.data.ownership==="external").map(x=>x.data.id));items=items.filter(x=>!x.data.source?keep.has(x.data.id):keep.has(String(x.data.source))&&keep.has(String(x.data.target)))}if(!items.length){setMsg("No infrastructure discovered yet.");return}setMsg("");cy.current?.destroy();cy.current=cytoscape({container:ref.current,elements:items as ElementDefinition[],style:[{selector:"node",style:{label:"data(label)","background-color":"#64748b","font-size":11,"text-wrap":"ellipsis","text-max-width":100,"text-outline-color":"#fff","text-outline-width":2}},{selector:"node[ownership='in_scope']",style:{"background-color":"#2563eb"}},{selector:"node[ownership='external']",style:{"background-color":"#d97706"}},{selector:"node[type='infrastructure_provider']",style:{shape:"hexagon","border-width":3,"border-color":"#7c3aed"}},{selector:"edge",style:{label:"data(label)",width:2,"line-color":"#cbd5e1","target-arrow-shape":"triangle","target-arrow-color":"#94a3b8","curve-style":"bezier","font-size":8}},{selector:".faded",style:{opacity:.18}},{selector:".selected",style:{"border-width":5,"border-color":"#111827"}}],layout:{name:"breadthfirst",directed:true,spacingFactor:1.5,animate:false}});cy.current.on("tap","node",e=>{cy.current?.elements().addClass("faded");e.target.removeClass("faded").addClass("selected");e.target.connectedEdges().removeClass("faded");e.target.connectedNodes().removeClass("faded");setSelected(e.target.data());setRelation(undefined)});cy.current.on("tap","edge",e=>{cy.current?.elements().addClass("faded");e.target.removeClass("faded").addClass("selected");e.target.connectedNodes().removeClass("faded");setRelation({...e.target.data(),label:e.target.data("label")});setSelected(undefined)})}).catch(()=>setMsg("Graph data could not be loaded."));return()=>{dead=true;cy.current?.destroy()}},[mode]);
const fit=()=>cy.current?.fit(undefined,40);const reset=()=>{cy.current?.removeClass("faded selected");cy.current?.layout({name:"breadthfirst",directed:true,spacingFactor:1.5}).run();setSelected(undefined);setRelation(undefined)};const zoomBy=(d:number)=>{if(cy.current)cy.current.zoom(Math.max(.3,Math.min(2.5,cy.current.zoom()+d)))};return <section><div className="graph-header"><div><span className="eyebrow">Infrastructure map</span><h1>Infrastructure graph</h1><p className="muted">Explore relationships across your authorized infrastructure.</p></div><div className="graph-controls"><button className="secondary small" onClick={()=>setMode("overview")}>Overview</button><button className="secondary small" onClick={()=>setMode("detailed")}>Detailed</button><button className="secondary small" onClick={fit}>Fit</button><button className="secondary small" onClick={reset}>Reset</button><button className="secondary small" onClick={()=>zoomBy(.2)}>+</button><button className="secondary small" onClick={()=>zoomBy(-.2)}>−</button></div></div><p className="muted">Blue: In scope · Orange: External · Gray: Unknown · Purple outline: Provider</p>{msg&&<p className="muted">{msg}</p>}<div className="graph-shell"><div ref={ref} className="graph" style={{minHeight:560}}/>{(selected||relation)&&<aside className="graph-detail"><button className="icon-button" onClick={()=>{setSelected(undefined);setRelation(undefined);cy.current?.elements().removeClass("faded selected")}}>×</button>{selected?<><span className="eyebrow">Asset</span><h2>{selected.displayName??selected.label}</h2><p>{selected.type} · {selected.ownership}</p><p>Confidence: {selected.confidence??"—"}</p><h3>Evidence</h3><pre>{JSON.stringify(selected.evidence??selected.metadata??{},null,2)}</pre></>:<><span className="eyebrow">Relationship</span><h2>{relation?.label}</h2><p>{relation?.source} → {relation?.target}</p><p>Confidence: {relation?.confidence??"—"}</p><h3>Evidence</h3><pre>{JSON.stringify(relation?.evidence??{},null,2)}</pre></>}</aside>}</div></section>}
